package Model;
// Generated 12-12-2017 03:23:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name="CARGO"
    ,schema="ADMIN_CRM"
)
public class Cargo  implements java.io.Serializable {


     private Integer idCargo;
     private String cargo;
     private Empleados empleados;
     private Set<Empleados> empleadoses = new HashSet<Empleados>(0);

    public Cargo() {
        this.idCargo=0;
        //this.empleados= new Empleados();
        
    }

	
    public Cargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public Cargo(Integer idCargo, String cargo, Set<Empleados> empleadoses ) {
       this.idCargo = idCargo;
       this.cargo = cargo;
       this.empleados = empleados;
    }
   
     @Id 

    
    @Column(name="ID_CARGO", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }

    
    @Column(name="CARGO", length=60)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargo")
    public Set<Empleados> getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set<Empleados> empleadoses) {
        this.empleadoses = empleadoses;
    }




}


