package Model;
// Generated 03-13-2018 02:30:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleCliente generated by hbm2java
 */
@Entity
@Table(name="DETALLE_CLIENTE"
    ,schema="ADMIN_CRM"
)
public class DetalleCliente  implements java.io.Serializable {


     private BigDecimal idDetalleCliente;
     private Cliente cliente;
     private String comentario;
     private String usuario;
     private Date fecha;

    public DetalleCliente() {
    }

	
    public DetalleCliente(BigDecimal idDetalleCliente, Cliente cliente) {
        this.idDetalleCliente = idDetalleCliente;
        this.cliente = cliente;
    }
    public DetalleCliente(BigDecimal idDetalleCliente, Cliente cliente, String comentario, String usuario, Date fecha) {
       this.idDetalleCliente = idDetalleCliente;
       this.cliente = cliente;
       this.comentario = comentario;
       this.usuario = usuario;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="ID_DETALLE_CLIENTE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdDetalleCliente() {
        return this.idDetalleCliente;
    }
    
    public void setIdDetalleCliente(BigDecimal idDetalleCliente) {
        this.idDetalleCliente = idDetalleCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENTE", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="COMENTARIO", length=400)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="USUARIO", length=80)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


