package Model;
// Generated 03-13-2018 02:30:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleNegocio generated by hbm2java
 */
@Entity
@Table(name="DETALLE_NEGOCIO"
    ,schema="ADMIN_CRM"
)
public class DetalleNegocio  implements java.io.Serializable {


     private BigDecimal idDetalleNegocio;
     private Negocio negocio;
     private String comentario;
     private Date fecha;
     private String usuario;
     private Date creaciondate;
     private Date modificaciondate;
     private String creadopor;
     private String modificadopor;

    public DetalleNegocio() {
    }

	
    public DetalleNegocio(BigDecimal idDetalleNegocio, Negocio negocio) {
        this.idDetalleNegocio = idDetalleNegocio;
        this.negocio = negocio;
    }
    public DetalleNegocio(BigDecimal idDetalleNegocio, Negocio negocio, String comentario, Date fecha, String usuario, Date creaciondate, Date modificaciondate, String creadopor, String modificadopor) {
       this.idDetalleNegocio = idDetalleNegocio;
       this.negocio = negocio;
       this.comentario = comentario;
       this.fecha = fecha;
       this.usuario = usuario;
       this.creaciondate = creaciondate;
       this.modificaciondate = modificaciondate;
       this.creadopor = creadopor;
       this.modificadopor = modificadopor;
    }
   
     @Id 

    
    @Column(name="ID_DETALLE_NEGOCIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdDetalleNegocio() {
        return this.idDetalleNegocio;
    }
    
    public void setIdDetalleNegocio(BigDecimal idDetalleNegocio) {
        this.idDetalleNegocio = idDetalleNegocio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_NEGOCIO", nullable=false)
    public Negocio getNegocio() {
        return this.negocio;
    }
    
    public void setNegocio(Negocio negocio) {
        this.negocio = negocio;
    }

    
    @Column(name="COMENTARIO", length=400)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="USUARIO", length=60)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREACIONDATE", length=7)
    public Date getCreaciondate() {
        return this.creaciondate;
    }
    
    public void setCreaciondate(Date creaciondate) {
        this.creaciondate = creaciondate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODIFICACIONDATE", length=7)
    public Date getModificaciondate() {
        return this.modificaciondate;
    }
    
    public void setModificaciondate(Date modificaciondate) {
        this.modificaciondate = modificaciondate;
    }

    
    @Column(name="CREADOPOR", length=75)
    public String getCreadopor() {
        return this.creadopor;
    }
    
    public void setCreadopor(String creadopor) {
        this.creadopor = creadopor;
    }

    
    @Column(name="MODIFICADOPOR", length=75)
    public String getModificadopor() {
        return this.modificadopor;
    }
    
    public void setModificadopor(String modificadopor) {
        this.modificadopor = modificadopor;
    }




}


