package Model;
// Generated 12-12-2017 03:23:15 PM by Hibernate Tools 4.3.1

//import java.math.BigDecimal;
import java.util.Date;
//import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name = "EMPLEADOS",
         schema = "ADMIN_CRM"
)
@NamedQueries(
        {
            @NamedQuery(name = "Empleados.buscarTodos", query = "SELECT d FROM Empleados d")
        }
)
public class Empleados implements java.io.Serializable {

    private Integer idEmpleado;
    private Cargo cargo;
    private Usuarios usuarios;
    private String nombre;
    private String apellido;
    private Date creaciondate;
    private Date modificaciondate;
    private String creadopor;
    private String modificadopor;
 ;

    public Empleados() {
        this.cargo = new Cargo();
        this.usuarios = new Usuarios();

    }

    public Empleados(Cargo cargo, Usuarios usuarios, String nombre, String apellido, Date creaciondate, Date modificaciondate, String creadopor, String modificadopor) {
        this.cargo = cargo;
        this.usuarios = usuarios;
        this.nombre = nombre;
        this.apellido = apellido;
        this.creaciondate = creaciondate;
        this.modificaciondate = modificaciondate;
        this.creadopor = creadopor;
        this.modificadopor = modificadopor;
    }

    @Id
    @SequenceGenerator(name = "seq", sequenceName = "EMPLEADO_AUTO_INC")
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "seq")
    @Column(name = "ID_EMPLEADO", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }

    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    @ManyToOne( fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_CARGO", nullable = false)
    public Cargo getCargo() {
        return this.cargo;
    }

    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

    @ManyToOne( fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID", nullable = false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    @Column(name = "NOMBRE", length = 100)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "APELLIDO", length = 100)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREACIONDATE", length = 7)
    public Date getCreaciondate() {
        return this.creaciondate;
    }

    public void setCreaciondate(Date creaciondate) {
        this.creaciondate = creaciondate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "MODIFICACIONDATE", length = 7)
    public Date getModificaciondate() {
        return this.modificaciondate;
    }

    public void setModificaciondate(Date modificaciondate) {
        this.modificaciondate = modificaciondate;
    }

    @Column(name = "CREADOPOR", length = 100)
    public String getCreadopor() {
        return this.creadopor;
    }

    public void setCreadopor(String creadopor) {
        this.creadopor = creadopor;
    }

    @Column(name = "MODIFICADOPOR", length = 100)
    public String getModificadopor() {
        return this.modificadopor;
    }

    public void setModificadopor(String modificadopor) {
        this.modificadopor = modificadopor;
    }

}
