package Model;
// Generated 01-09-2018 11:33:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoNegocio generated by hbm2java
 */
@Entity
@Table(name="ESTADO_NEGOCIO"
    ,schema="ADMIN_CRM"
)
public class EstadoNegocio  implements java.io.Serializable {


     private BigDecimal idEstadoNegocio;
     private String estadoNegocio;
     private Set<Negocio> negocios = new HashSet<Negocio>(0);

    public EstadoNegocio() {
    }

	
    public EstadoNegocio(BigDecimal idEstadoNegocio) {
        this.idEstadoNegocio = idEstadoNegocio;
    }
    public EstadoNegocio(BigDecimal idEstadoNegocio, String estadoNegocio, Set<Negocio> negocios) {
       this.idEstadoNegocio = idEstadoNegocio;
       this.estadoNegocio = estadoNegocio;
       this.negocios = negocios;
    }
   
     @Id 

    
    @Column(name="ID_ESTADO_NEGOCIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdEstadoNegocio() {
        return this.idEstadoNegocio;
    }
    
    public void setIdEstadoNegocio(BigDecimal idEstadoNegocio) {
        this.idEstadoNegocio = idEstadoNegocio;
    }

    
    @Column(name="ESTADO_NEGOCIO", length=40)
    public String getEstadoNegocio() {
        return this.estadoNegocio;
    }
    
    public void setEstadoNegocio(String estadoNegocio) {
        this.estadoNegocio = estadoNegocio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoNegocio")
    public Set<Negocio> getNegocios() {
        return this.negocios;
    }
    
    public void setNegocios(Set<Negocio> negocios) {
        this.negocios = negocios;
    }




}


