package Model;
// Generated 03-13-2018 02:30:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fabricante generated by hbm2java
 */
@Entity
@Table(name="FABRICANTE"
    ,schema="ADMIN_CRM"
)
public class Fabricante  implements java.io.Serializable {


     private BigDecimal idFabricante;
     private String nombreFabricante;
     private Date creaciondate;
     private Date modificaciondate;
     private String creadopor;
     private String modificadopor;
     private String status;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public Fabricante() {
    }

	
    public Fabricante(BigDecimal idFabricante) {
        this.idFabricante = idFabricante;
    }
    public Fabricante(BigDecimal idFabricante, String nombreFabricante, Date creaciondate, Date modificaciondate, String creadopor, String modificadopor, String status, Set<Productos> productoses) {
       this.idFabricante = idFabricante;
       this.nombreFabricante = nombreFabricante;
       this.creaciondate = creaciondate;
       this.modificaciondate = modificaciondate;
       this.creadopor = creadopor;
       this.modificadopor = modificadopor;
       this.status = status;
       this.productoses = productoses;
    }
   
     @Id 

    
    @Column(name="ID_FABRICANTE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdFabricante() {
        return this.idFabricante;
    }
    
    public void setIdFabricante(BigDecimal idFabricante) {
        this.idFabricante = idFabricante;
    }

    
    @Column(name="NOMBRE_FABRICANTE", length=48)
    public String getNombreFabricante() {
        return this.nombreFabricante;
    }
    
    public void setNombreFabricante(String nombreFabricante) {
        this.nombreFabricante = nombreFabricante;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREACIONDATE", length=7)
    public Date getCreaciondate() {
        return this.creaciondate;
    }
    
    public void setCreaciondate(Date creaciondate) {
        this.creaciondate = creaciondate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODIFICACIONDATE", length=7)
    public Date getModificaciondate() {
        return this.modificaciondate;
    }
    
    public void setModificaciondate(Date modificaciondate) {
        this.modificaciondate = modificaciondate;
    }

    
    @Column(name="CREADOPOR", length=75)
    public String getCreadopor() {
        return this.creadopor;
    }
    
    public void setCreadopor(String creadopor) {
        this.creadopor = creadopor;
    }

    
    @Column(name="MODIFICADOPOR", length=75)
    public String getModificadopor() {
        return this.modificadopor;
    }
    
    public void setModificadopor(String modificadopor) {
        this.modificadopor = modificadopor;
    }

    
    @Column(name="STATUS", length=25)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fabricante")
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


