package Model;
// Generated 01-31-2018 04:23:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fase generated by hbm2java
 */
@Entity
@Table(name="FASE"
    ,schema="ADMIN_CRM"
)
public class Fase  implements java.io.Serializable {


     private Integer idFase;
     private String fase;
     private Set<Oportunidades> oportunidadeses = new HashSet<Oportunidades>(0);

    public Fase() {
    }

	
    
    public Fase(String fase, Set<Oportunidades> oportunidadeses) {
      
       this.fase = fase;
       this.oportunidadeses = oportunidadeses;
    }
   
     @Id 

    
    @Column(name="ID_FASE", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdFase() {
        return this.idFase;
    }
    
    public void setIdFase(Integer idFase) {
        this.idFase = idFase;
    }

    
    @Column(name="FASE", length=80)
    public String getFase() {
        return this.fase;
    }
    
    public void setFase(String fase) {
        this.fase = fase;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fase")
    public Set<Oportunidades> getOportunidadeses() {
        return this.oportunidadeses;
    }
    
    public void setOportunidadeses(Set<Oportunidades> oportunidadeses) {
        this.oportunidadeses = oportunidadeses;
    }




}


