package Model;
// Generated 03-13-2018 02:30:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductosCliente generated by hbm2java
 */
@Entity
@Table(name="PRODUCTOS_CLIENTE"
    ,schema="ADMIN_CRM"
)
public class ProductosCliente  implements java.io.Serializable {


     private BigDecimal idProductosCliente;
     private Cliente cliente;
     private Productos productos;
     private String productosCliente;

    public ProductosCliente() {
    }

	
    public ProductosCliente(BigDecimal idProductosCliente, Cliente cliente, Productos productos) {
        this.idProductosCliente = idProductosCliente;
        this.cliente = cliente;
        this.productos = productos;
    }
    public ProductosCliente(BigDecimal idProductosCliente, Cliente cliente, Productos productos, String productosCliente) {
       this.idProductosCliente = idProductosCliente;
       this.cliente = cliente;
       this.productos = productos;
       this.productosCliente = productosCliente;
    }
   
     @Id 

    
    @Column(name="ID_PRODUCTOS_CLIENTE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdProductosCliente() {
        return this.idProductosCliente;
    }
    
    public void setIdProductosCliente(BigDecimal idProductosCliente) {
        this.idProductosCliente = idProductosCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENTE", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRODUCTO", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

    
    @Column(name="PRODUCTOS_CLIENTE", length=50)
    public String getProductosCliente() {
        return this.productosCliente;
    }
    
    public void setProductosCliente(String productosCliente) {
        this.productosCliente = productosCliente;
    }




}


