package Model;
// Generated 01-09-2018 11:33:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoCliente generated by hbm2java
 */
@Entity
@Table(name="TIPO_CLIENTE"
    ,schema="ADMIN_CRM"
)
public class TipoCliente  implements java.io.Serializable {


     private BigDecimal idTipoCliente;
     private String tipoCliente;

    public TipoCliente() {
    }

	
    public TipoCliente(BigDecimal idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }
    public TipoCliente(BigDecimal idTipoCliente, String tipoCliente) {
       this.idTipoCliente = idTipoCliente;
       this.tipoCliente = tipoCliente;
    }
   
     @Id 

    
    @Column(name="ID_TIPO_CLIENTE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdTipoCliente() {
        return this.idTipoCliente;
    }
    
    public void setIdTipoCliente(BigDecimal idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }

    
    @Column(name="TIPO_CLIENTE", length=60)
    public String getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(String tipoCliente) {
        this.tipoCliente = tipoCliente;
    }




}


